# - name: install maven
#   yum: 
#     name: maven
#     state: latest


- name: Download Apache Maven 
  get_url:
    url=http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
    dest=/opt/maven/apache-maven-3.6.1-bin.tar.gz

     
- name: Untar Maven 
  shell: chdir=/opt/maven creates=/opt/maven/apache-maven-3.6.1-bin.tar.gz -zxf apache-maven-3.6.1-bin.tar.gz -C /opt/maven    