# - name: download terrafrom zip file
#   get_url:
#     url: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
#     dest: /opt/terraform
#     mode: "0775"


- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /opt/terraform/terraform_0.11.13_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
