# - name: Download tomcat file from internet
#   get_url:
#     url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.42/bin/apache-tomcat-8.5.42.tar.gz
#     dest: /opt/tomcat
#     mode: '0775'


# - name: unarchive downloaded tomcat file
#   unarchive:
#     src: /opt/tomcat/apache-tomcat-8.5.42.tar.gz
#     dest: /opt/tomcat/

- name: Execute the script
  command: sh /opt/tomcat/apache-tomcat-8/bin/start.sh
