# - name: install all basic packages
#   yum:
#     name: net-tools
#     state: latest

# - name: upadate all packages
#   yum:
#     name: '*'
#     state: latest


# - name: install java
#   yum:
#     name: java-1.8.0-openjdk
#     state: latest



# - name: install gcc-c++ make for node.js
#   yum:
#     name: gcc-c++ make
#     state: latest    